### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by poisson-myfish** [sebbekarlsson/gpp#11]
In the README you said you don't have a licence. Well, you just want people to do anything with it.

But in that case, you should better add a licence like MIT, which is very permissive.

The reason is, without a licence you don't say anything. So you basically say, do whatever. You don't say you don't have warranty, and you're not responsible for any damage.

This is a bad move, since someone can call you out on a bug and say that it doesn't work as it said in the README, do they can even sue you.

I completely understand your intentions, and I think it's nice. But you should really consider a licence.

Cheers.

_Note: This is **not** legal advice_

**Comment by sebbekarlsson** [comment]
@poisson-myfish  Thank you for informing me, you care correct. A license is important.
I have now added a license
